feat: find executable filename to address #16
ashb/sphinx-argparse pull request #17
Opened 2022-05-04 17:56 UTC by tsutterley

should address #4 for finding relative paths

2022-11-10 18:21 UTC, ashb requested changes
Please ping/mention me when you've made the changes.

(Sorry for not noticing this earlier, I didn't have notifications on this repo!)

2022-11-10 18:21 UTC, ashb commented on sphinxarg/ext.py
> +from distutils.spawn import find_executable
We can't use distutils, it's going away in Py 3.12:

> [distutils](https://docs.python.org/3/library/distutils.html#module-distutils) is deprecated with removal planned for Python 3.12. See the [What’s New](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated) entry for more information.

2022-11-10 18:35 UTC, tsutterley commented on sphinxarg/ext.py
> +            return f
hey @ashb no worries on the timing. I think I have all your requested changes in with 5bf2fc6

2022-11-10 22:43 UTC, ashb approved these changes

2022-11-10 22:51 UTC, ashb commented on sphinxarg/ext.py
> +        except (OSError, FileNotFoundError):
```suggestion
        except OSError:
```

2022-11-10 22:51 UTC, ashb commented on sphinxarg/ext.py
> +        except (OSError, FileNotFoundError):
```suggestion
        except OSError:
```

2022-11-10 22:51 UTC, ashb commented on sphinxarg/ext.py
> +        except (OSError, FileNotFoundError):
```suggestion
        except OSError:
```

2022-11-10 22:55 UTC, ashb commented on sphinxarg/ext.py
> +import shutil
```suggestion
import shutil
import sys
from argparse import ArgumentParser
```

2022-11-10 22:55 UTC, tsutterley commented
thanks for putting in the final touches @ashb!

2022-11-10 22:56 UTC, ashb commented
@tsutterley Not a problem, I'll get a release out today/tomorrow with this in. (And a bump to py3.7 as min requirement too.)

2022-11-10 22:57 UTC, merged

2022-11-12 18:35 UTC, ashb commented
@tsutterley released as 0.4.0